### PR TITLE
Added unprotected retrieval of issues

### PR DESCRIPTION
**Pull request by Ismail731404**

### CODE REVIEW

**Comment by SchawnnDev** [comment]
difference between #153 and #154 (this one) ?

**Comment by Ismail731404** [comment]
Branch #153 is targeted for PROD, utilizing a previous version of the engine.

**Comment by SchawnnDev** [comment]
> Branch #153 is targeted for PROD, utilizing a previous version of the engine.

they is no need to merge #153 ?

**Review by SchawnnDev — APPROVED** [review]

**Comment by Ismail731404** [comment]
> ###
> [Dec 14, 2023](#issuecomment-1855865621)

Effectively

**Pull request merged**
